#!/bin/bash

case "$1" in
"client")
  cargo run --bin client -- ${@:2}
  ;;
"server")
  cargo run --bin server -- ${@:2}
  ;;
*)
  echo "Usage:
$0 server <ip:port>
$0 client <gameid> [ip:port]"
  exit 1
  ;;
esac
